#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-elasticsearch
Version  : 1
Release  : 1
URL      : https://repo.maven.apache.org/maven2/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1-sources.jar
Source0  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1-sources.jar
Source1  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1.jar
Source2  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1.pom
Source3  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1/elasticsearch-rest-high-level-client-6.3.1.jar
Source4  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1/elasticsearch-rest-high-level-client-6.3.1.pom
Source5  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/rest/5.1.2/rest-5.1.2.jar
Source6  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/rest/5.1.2/rest-5.1.2.pom
Source7  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/transport/5.1.2/transport-5.1.2.jar
Source8  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/transport/5.1.2/transport-5.1.2.pom
Source9  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/transport/6.3.1/transport-6.3.1.jar
Source10  : https://repo.maven.apache.org/maven2/org/elasticsearch/client/transport/6.3.1/transport-6.3.1.pom
Source11  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-cli/6.3.1/elasticsearch-cli-6.3.1.jar
Source12  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-cli/6.3.1/elasticsearch-cli-6.3.1.pom
Source13  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-core/6.3.1/elasticsearch-core-6.3.1.jar
Source14  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-core/6.3.1/elasticsearch-core-6.3.1.pom
Source15  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-secure-sm/6.3.1/elasticsearch-secure-sm-6.3.1.jar
Source16  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-secure-sm/6.3.1/elasticsearch-secure-sm-6.3.1.pom
Source17  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-x-content/6.3.1/elasticsearch-x-content-6.3.1.jar
Source18  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch-x-content/6.3.1/elasticsearch-x-content-6.3.1.pom
Source19  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/1.7.1/elasticsearch-1.7.1.jar
Source20  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/1.7.1/elasticsearch-1.7.1.pom
Source21  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/2.3.5/elasticsearch-2.3.5.jar
Source22  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/2.3.5/elasticsearch-2.3.5.pom
Source23  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/5.1.2/elasticsearch-5.1.2.jar
Source24  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/5.1.2/elasticsearch-5.1.2.pom
Source25  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/6.3.1/elasticsearch-6.3.1.jar
Source26  : https://repo.maven.apache.org/maven2/org/elasticsearch/elasticsearch/6.3.1/elasticsearch-6.3.1.pom
Source27  : https://repo.maven.apache.org/maven2/org/elasticsearch/parent/2.3.5/parent-2.3.5.pom
Source28  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1/aggs-matrix-stats-client-6.3.1.jar
Source29  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1/aggs-matrix-stats-client-6.3.1.pom
Source30  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/lang-mustache-client/5.1.2/lang-mustache-client-5.1.2.jar
Source31  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/lang-mustache-client/5.1.2/lang-mustache-client-5.1.2.pom
Source32  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/lang-mustache-client/6.3.1/lang-mustache-client-6.3.1.jar
Source33  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/lang-mustache-client/6.3.1/lang-mustache-client-6.3.1.pom
Source34  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/parent-join-client/6.3.1/parent-join-client-6.3.1.jar
Source35  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/parent-join-client/6.3.1/parent-join-client-6.3.1.pom
Source36  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/percolator-client/5.1.2/percolator-client-5.1.2.jar
Source37  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/percolator-client/5.1.2/percolator-client-5.1.2.pom
Source38  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/percolator-client/6.3.1/percolator-client-6.3.1.jar
Source39  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/percolator-client/6.3.1/percolator-client-6.3.1.pom
Source40  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/rank-eval-client/6.3.1/rank-eval-client-6.3.1.jar
Source41  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/rank-eval-client/6.3.1/rank-eval-client-6.3.1.pom
Source42  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/reindex-client/5.1.2/reindex-client-5.1.2.jar
Source43  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/reindex-client/5.1.2/reindex-client-5.1.2.pom
Source44  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/reindex-client/6.3.1/reindex-client-6.3.1.jar
Source45  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/reindex-client/6.3.1/reindex-client-6.3.1.pom
Source46  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/transport-netty3-client/5.1.2/transport-netty3-client-5.1.2.jar
Source47  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/transport-netty3-client/5.1.2/transport-netty3-client-5.1.2.pom
Source48  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/transport-netty4-client/5.1.2/transport-netty4-client-5.1.2.jar
Source49  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/transport-netty4-client/5.1.2/transport-netty4-client-5.1.2.pom
Source50  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/transport-netty4-client/6.3.1/transport-netty4-client-6.3.1.jar
Source51  : https://repo.maven.apache.org/maven2/org/elasticsearch/plugin/transport-netty4-client/6.3.1/transport-netty4-client-6.3.1.pom
Source52  : https://repo.maven.apache.org/maven2/org/elasticsearch/securesm/1.0/securesm-1.0.jar
Source53  : https://repo.maven.apache.org/maven2/org/elasticsearch/securesm/1.0/securesm-1.0.pom
Source54  : https://repo.maven.apache.org/maven2/org/elasticsearch/securesm/1.1/securesm-1.1.jar
Source55  : https://repo.maven.apache.org/maven2/org/elasticsearch/securesm/1.1/securesm-1.1.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-elasticsearch-data = %{version}-%{release}
Requires: mvn-elasticsearch-license = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-elasticsearch package.
Group: Data

%description data
data components for the mvn-elasticsearch package.


%package license
Summary: license components for the mvn-elasticsearch package.
Group: Default

%description license
license components for the mvn-elasticsearch package.


%prep
%setup -q -n META-INF

%build

%install
mkdir -p %{buildroot}/usr/share/package-licenses/mvn-elasticsearch
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/mvn-elasticsearch/LICENSE.txt
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1
cp %{SOURCE0} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1-sources.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1
cp %{SOURCE2} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1
cp %{SOURCE3} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1/elasticsearch-rest-high-level-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1
cp %{SOURCE4} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1/elasticsearch-rest-high-level-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/rest/5.1.2
cp %{SOURCE5} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/rest/5.1.2/rest-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/rest/5.1.2
cp %{SOURCE6} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/rest/5.1.2/rest-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/5.1.2
cp %{SOURCE7} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/5.1.2/transport-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/5.1.2
cp %{SOURCE8} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/5.1.2/transport-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/6.3.1
cp %{SOURCE9} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/6.3.1/transport-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/6.3.1
cp %{SOURCE10} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/client/transport/6.3.1/transport-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-cli/6.3.1
cp %{SOURCE11} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-cli/6.3.1/elasticsearch-cli-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-cli/6.3.1
cp %{SOURCE12} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-cli/6.3.1/elasticsearch-cli-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-core/6.3.1
cp %{SOURCE13} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-core/6.3.1/elasticsearch-core-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-core/6.3.1
cp %{SOURCE14} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-core/6.3.1/elasticsearch-core-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-secure-sm/6.3.1
cp %{SOURCE15} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-secure-sm/6.3.1/elasticsearch-secure-sm-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-secure-sm/6.3.1
cp %{SOURCE16} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-secure-sm/6.3.1/elasticsearch-secure-sm-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-x-content/6.3.1
cp %{SOURCE17} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-x-content/6.3.1/elasticsearch-x-content-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-x-content/6.3.1
cp %{SOURCE18} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-x-content/6.3.1/elasticsearch-x-content-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/1.7.1
cp %{SOURCE19} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/1.7.1/elasticsearch-1.7.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/1.7.1
cp %{SOURCE20} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/1.7.1/elasticsearch-1.7.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/2.3.5
cp %{SOURCE21} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/2.3.5/elasticsearch-2.3.5.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/2.3.5
cp %{SOURCE22} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/2.3.5/elasticsearch-2.3.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/5.1.2
cp %{SOURCE23} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/5.1.2/elasticsearch-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/5.1.2
cp %{SOURCE24} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/5.1.2/elasticsearch-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/6.3.1
cp %{SOURCE25} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/6.3.1/elasticsearch-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/6.3.1
cp %{SOURCE26} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/6.3.1/elasticsearch-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/parent/2.3.5
cp %{SOURCE27} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/parent/2.3.5/parent-2.3.5.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1
cp %{SOURCE28} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1/aggs-matrix-stats-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1
cp %{SOURCE29} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1/aggs-matrix-stats-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/5.1.2
cp %{SOURCE30} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/5.1.2/lang-mustache-client-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/5.1.2
cp %{SOURCE31} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/5.1.2/lang-mustache-client-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/6.3.1
cp %{SOURCE32} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/6.3.1/lang-mustache-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/6.3.1
cp %{SOURCE33} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/6.3.1/lang-mustache-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/parent-join-client/6.3.1
cp %{SOURCE34} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/parent-join-client/6.3.1/parent-join-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/parent-join-client/6.3.1
cp %{SOURCE35} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/parent-join-client/6.3.1/parent-join-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/5.1.2
cp %{SOURCE36} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/5.1.2/percolator-client-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/5.1.2
cp %{SOURCE37} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/5.1.2/percolator-client-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/6.3.1
cp %{SOURCE38} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/6.3.1/percolator-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/6.3.1
cp %{SOURCE39} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/6.3.1/percolator-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/rank-eval-client/6.3.1
cp %{SOURCE40} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/rank-eval-client/6.3.1/rank-eval-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/rank-eval-client/6.3.1
cp %{SOURCE41} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/rank-eval-client/6.3.1/rank-eval-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/5.1.2
cp %{SOURCE42} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/5.1.2/reindex-client-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/5.1.2
cp %{SOURCE43} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/5.1.2/reindex-client-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/6.3.1
cp %{SOURCE44} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/6.3.1/reindex-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/6.3.1
cp %{SOURCE45} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/6.3.1/reindex-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty3-client/5.1.2
cp %{SOURCE46} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty3-client/5.1.2/transport-netty3-client-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty3-client/5.1.2
cp %{SOURCE47} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty3-client/5.1.2/transport-netty3-client-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/5.1.2
cp %{SOURCE48} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/5.1.2/transport-netty4-client-5.1.2.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/5.1.2
cp %{SOURCE49} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/5.1.2/transport-netty4-client-5.1.2.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/6.3.1
cp %{SOURCE50} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/6.3.1/transport-netty4-client-6.3.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/6.3.1
cp %{SOURCE51} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/6.3.1/transport-netty4-client-6.3.1.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.0
cp %{SOURCE52} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.0/securesm-1.0.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.0
cp %{SOURCE53} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.0/securesm-1.0.pom

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.1
cp %{SOURCE54} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.1/securesm-1.1.jar

mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.1
cp %{SOURCE55} %{buildroot}/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.1/securesm-1.1.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1-sources.jar
/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-client/6.3.1/elasticsearch-rest-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1/elasticsearch-rest-high-level-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/client/elasticsearch-rest-high-level-client/6.3.1/elasticsearch-rest-high-level-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/client/rest/5.1.2/rest-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/client/rest/5.1.2/rest-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/client/transport/5.1.2/transport-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/client/transport/5.1.2/transport-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/client/transport/6.3.1/transport-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/client/transport/6.3.1/transport-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-cli/6.3.1/elasticsearch-cli-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-cli/6.3.1/elasticsearch-cli-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-core/6.3.1/elasticsearch-core-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-core/6.3.1/elasticsearch-core-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-secure-sm/6.3.1/elasticsearch-secure-sm-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-secure-sm/6.3.1/elasticsearch-secure-sm-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-x-content/6.3.1/elasticsearch-x-content-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch-x-content/6.3.1/elasticsearch-x-content-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/1.7.1/elasticsearch-1.7.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/1.7.1/elasticsearch-1.7.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/2.3.5/elasticsearch-2.3.5.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/2.3.5/elasticsearch-2.3.5.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/5.1.2/elasticsearch-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/5.1.2/elasticsearch-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/6.3.1/elasticsearch-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/elasticsearch/6.3.1/elasticsearch-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/parent/2.3.5/parent-2.3.5.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1/aggs-matrix-stats-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/aggs-matrix-stats-client/6.3.1/aggs-matrix-stats-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/5.1.2/lang-mustache-client-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/5.1.2/lang-mustache-client-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/6.3.1/lang-mustache-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/lang-mustache-client/6.3.1/lang-mustache-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/parent-join-client/6.3.1/parent-join-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/parent-join-client/6.3.1/parent-join-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/5.1.2/percolator-client-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/5.1.2/percolator-client-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/6.3.1/percolator-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/percolator-client/6.3.1/percolator-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/rank-eval-client/6.3.1/rank-eval-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/rank-eval-client/6.3.1/rank-eval-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/5.1.2/reindex-client-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/5.1.2/reindex-client-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/6.3.1/reindex-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/reindex-client/6.3.1/reindex-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty3-client/5.1.2/transport-netty3-client-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty3-client/5.1.2/transport-netty3-client-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/5.1.2/transport-netty4-client-5.1.2.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/5.1.2/transport-netty4-client-5.1.2.pom
/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/6.3.1/transport-netty4-client-6.3.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/plugin/transport-netty4-client/6.3.1/transport-netty4-client-6.3.1.pom
/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.0/securesm-1.0.jar
/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.0/securesm-1.0.pom
/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.1/securesm-1.1.jar
/usr/share/java/.m2/repository/org/elasticsearch/securesm/1.1/securesm-1.1.pom

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/mvn-elasticsearch/LICENSE.txt
